/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Task Tracker API
 * OpenAPI spec version: 1.0.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export type TaskStatus = typeof TaskStatus[keyof typeof TaskStatus];


export const TaskStatus = {
  todo: 'todo',
  'in-progress': 'in-progress',
  done: 'done',
} as const;

export type TaskPriority = typeof TaskPriority[keyof typeof TaskPriority];


export const TaskPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface Task {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  /** @nullable */
  dueDate?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type TaskInputStatus = typeof TaskInputStatus[keyof typeof TaskInputStatus];


export const TaskInputStatus = {
  todo: 'todo',
  'in-progress': 'in-progress',
  done: 'done',
} as const;

export type TaskInputPriority = typeof TaskInputPriority[keyof typeof TaskInputPriority];


export const TaskInputPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface TaskInput {
  /** @minLength 1 */
  title: string;
  description?: string;
  status?: TaskInputStatus;
  priority?: TaskInputPriority;
  dueDate?: string;
}

export type TaskUpdateStatus = typeof TaskUpdateStatus[keyof typeof TaskUpdateStatus];


export const TaskUpdateStatus = {
  todo: 'todo',
  'in-progress': 'in-progress',
  done: 'done',
} as const;

export type TaskUpdatePriority = typeof TaskUpdatePriority[keyof typeof TaskUpdatePriority];


export const TaskUpdatePriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface TaskUpdate {
  /** @minLength 1 */
  title?: string;
  /** @nullable */
  description?: string | null;
  status?: TaskUpdateStatus;
  priority?: TaskUpdatePriority;
  /** @nullable */
  dueDate?: string | null;
}

export type TaskStatsByStatus = {
  todo: number;
  inProgress: number;
  done: number;
};

export type TaskStatsByPriority = {
  low: number;
  medium: number;
  high: number;
};

export interface TaskStats {
  total: number;
  byStatus: TaskStatsByStatus;
  byPriority: TaskStatsByPriority;
  overdue: number;
}

export type ListTasksParams = {
status?: ListTasksStatus;
priority?: ListTasksPriority;
sortBy?: ListTasksSortBy;
sortOrder?: ListTasksSortOrder;
search?: string;
};

export type ListTasksStatus = typeof ListTasksStatus[keyof typeof ListTasksStatus];


export const ListTasksStatus = {
  todo: 'todo',
  'in-progress': 'in-progress',
  done: 'done',
} as const;

export type ListTasksPriority = typeof ListTasksPriority[keyof typeof ListTasksPriority];


export const ListTasksPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export type ListTasksSortBy = typeof ListTasksSortBy[keyof typeof ListTasksSortBy];


export const ListTasksSortBy = {
  createdAt: 'createdAt',
  dueDate: 'dueDate',
  priority: 'priority',
  title: 'title',
} as const;

export type ListTasksSortOrder = typeof ListTasksSortOrder[keyof typeof ListTasksSortOrder];


export const ListTasksSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

